name: Build Android

env:
  cacheId: '6' # increment to expire the cache

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compile-sdk: [30]
        build-tools: [30.0.2]
        sdk-tools: [4333796]
    steps:
      - uses: actions/checkout@v1

      - name: Configure node
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          registry-url: 'https://registry.npmjs.org'

      - name: setup ubuntu
        run: |
          sudo apt-get --quiet update --yes
          sudo apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: download Android SDK
        working-directory: ./app/android
        run: |
          wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${{ matrix.sdk-tools }}.zip
          unzip -d android-sdk-linux android-sdk.zip
          sudo mkdir -p /root/.android
          sudo touch /root/.android/repositories.cfg
          echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${{ matrix.compile-sdk }}" >/dev/null
          echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" >/dev/null
          echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${{ matrix.build-tools }}" >/dev/null
          export ANDROID_HOME=$PWD/android-sdk-linux
          export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
          chmod +x ./gradlew
          set +o pipefail
          yes | android-sdk-linux/tools/bin/sdkmanager --licenses
          set -o pipefail

        # GitHub recommends not caching node_modules but rather
        # .npm because it can break across Node versions and
        #  won't work with npm ci.
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.cacheId }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cacheId }}-

      - name: Install dependencies
        run: |
          npm version && npm ci &&
          cd ./app && npm ci

      - name: Android Debug Build
        working-directory: ./app/android
        run: ./gradlew bundleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: ./app/android/app/build/outputs/apk/release/


